### PR TITLE
"Add a f***up counter for teams", crit bug fixed

### PR DESCRIPTION
**Pull request by Mr-Smarty**
Added the "f***up counter for teams" requested
fixed critical bug with slash command permission registering

### CODE REVIEW

**Comment by Mr-Smarty** [comment]
It seems the tsc check broke

**Comment by Mr-Smarty** [comment]
It seems the tsc check and the prettier format check broke

**Comment by XboxBedrock** [comment]
f***up counter

**Comment by XboxBedrock** [comment]
Seems great ill be merging it

**Pull request merged**
