### PR TITLE
More efficient kick command, better aliases and more efficient auto responses 

### PR DESCRIPTION
**Pull request by dy-dx-1**
A better kick command: `=yeeti` (only needs to specify username, pfp or status and it will send
`Please change your [VARIABLE] and then you can come back`  
as reason. 

Better aliases for multiple commands, suggestions were taken from the mod team 

Some auto responses added to make support easier 

Idk why the fuck package-lock.json got thousands of line deleted so check what's up with that pls lol

### CODE REVIEW

**Review by cAttte — COMMENTED** [review]
you're stupid (jk 😘)

**Comment by dy-dx-1** [comment]
ur so mean and uncool and mean and ruce and i hate you anda  fuck anda tou

**Comment by RudeYeti** [comment]
This command looks amazing.

**Comment by celery6** [comment]
Hi, I have been closely following the progression of this PR and I would like to input my opinion. I believe this improvement would greatly benefit the bot. Thank you.

**Comment by cAttte** [comment]
@dy-dx-1 this is illegal

**Comment by dy-dx-1** [comment]
@cAttte the people have spoken!

**Comment by Milo123459** [comment]
-1, The "gtfo" alias is innapropriate. SMH.

**Comment by fnionn** [comment]
> -1, The "gtfo" alias is innapropriate. SMH.

no

**Comment by Milo123459** [comment]
> > -1, The "gtfo" alias is innapropriate. SMH.
> 
> no

yes

**Comment by Milo123459** [comment]
hello staff team

**Comment by Milo123459** [comment]
how are you

**Comment by Milo123459** [comment]
im good thanks

**Comment by Milo123459** [comment]
fnionn is dying

**Comment by Milo123459** [comment]
help him

**Comment by Milo123459** [comment]
FNIONN THATS NOT VERY NICE OF YOU

**Comment by Milo123459** [comment]
I AM TYPING FNIONN

**Comment by Milo123459** [comment]
NO U

**Comment by Milo123459** [comment]
NO DONT UPDATE THE README

**Comment by Milo123459** [comment]
THE README IS FINE

**Comment by Milo123459** [comment]
WE ARE ON A CALL

**Comment by Milo123459** [comment]
FYI

**Comment by Milo123459** [comment]
BTW I NEVER GOT A RESPONSE BACK HOW ARE YOU

**Comment by fnionn** [comment]
> 
> 
> BTW I NEVER GOT A RESPONSE BACK HOW ARE YOU

AM GOOD

**Comment by Milo123459** [comment]
> > BTW I NEVER GOT A RESPONSE BACK HOW ARE YOU
> 
> AM GOOD

GOOD

**Comment by Nudelsuppe42** [comment]
Your spaming smh 😕

**Comment by Milo123459** [comment]
No I'm not

**Comment by Milo123459** [comment]
smh

**Comment by Milo123459** [comment]
s

**Comment by Milo123459** [comment]
m

**Comment by Milo123459** [comment]
h

**Comment by fnionn** [comment]
STOp

**Comment by Milo123459** [comment]
NO

**Comment by Milo123459** [comment]
ok this was fun bye everyone 👋

**Comment by Nudelsuppe42** [comment]
Thanks

**Comment by Milo123459** [comment]
btw fnionn is not sorry
last thing I had to say

**Comment by dy-dx-1** [comment]
wow censorship

**Comment by cAttte** [comment]
this is literally 1984 but please stop talking here there's already enough spam with the deleted comments :+1:

**Comment by funnion** [comment]
Closing due to Inactivity.

**Pull request closed without merging**
