### PR TITLE
Delete Messages Command

### PR DESCRIPTION
**Pull request by XboxBedrock**
#1 
The command can delete messages
usage:
<channel> <messageID>

### CODE REVIEW

**Comment by XboxBedrock** [comment]
#1

**Comment by rudeyeti** [comment]
I don't think this is necessary because all staff have delete message permissions.

**Comment by cAttte** [comment]
@rudeyeti arc requested it for revamp, as staff doesn't have the Manage Messages permission in the info channels (and asking admins is usually not the most fruitful thing)

**Comment by cAttte** [comment]
sorry, but i'm going to have to close this PR. i had other plans for this (a `message` command with `edit`/`delete` subcommands and message link parsing), and this is not how i want the commands to be structured. thanks a lot for contributing, though! and, next time, please run the build, lint, and format scripts before committing (and test the command, because this won't actually work!).

**Comment by XboxBedrock** [comment]
Very interesting, I even tested it in a server and it worked.

**Comment by cAttte** [comment]
yeah, turns out `Args#consumeChannel()` doesn't actually consume the first arg, it just gets it (which was the root of my confusion), so, i'll have to fix that!

**Pull request closed without merging**
